import talib

CDL_PATTERNS = {
    'Abandoned Baby': talib.CDLABANDONEDBABY,
    'Advance Block': talib.CDLADVANCEBLOCK,
    'Belt-hold': talib.CDLBELTHOLD,
    'Breakaway': talib.CDLBREAKAWAY,
    'Closing Marubozu': talib.CDLCLOSINGMARUBOZU,
    'Concealing Baby Swallow': talib.CDLCONCEALBABYSWALL,
    'Counterattack': talib.CDLCOUNTERATTACK,
    'Dark Cloud Cover': talib.CDLDARKCLOUDCOVER,
    'Doji': talib.CDLDOJI,
    'Doji Star': talib.CDLDOJISTAR,
    'Dragonfly Doji': talib.CDLDRAGONFLYDOJI,
    'Engulfing Pattern': talib.CDLENGULFING,
    'Evening Doji Star': talib.CDLEVENINGDOJISTAR,
    'Evening Star': talib.CDLEVENINGSTAR,
    'Gravestone Doji': talib.CDLGRAVESTONEDOJI,
    'Hammer': talib.CDLHAMMER,
    'Hanging Man': talib.CDLHANGINGMAN,
    'Harami Cross Pattern': talib.CDLHARAMICROSS,
    'Harami Pattern': talib.CDLHARAMI,
    'High-Wave Candle': talib.CDLHIGHWAVE,
    'Hikkake Pattern': talib.CDLHIKKAKE,
    'Homing Pigeon': talib.CDLHOMINGPIGEON,
    'Identical Three Crows': talib.CDLIDENTICAL3CROWS,
    'In-Neck Pattern': talib.CDLINNECK,
    'Inverted Hammer': talib.CDLINVERTEDHAMMER,
    'Kicking': talib.CDLKICKING,
    'Kicking - bull/bear determined by the longer marubozu': talib.CDLKICKINGBYLENGTH,
    'Ladder Bottom': talib.CDLLADDERBOTTOM,
    'Long Legged Doji': talib.CDLLONGLEGGEDDOJI,
    'Long Line Candle': talib.CDLLONGLINE,
    'Marubozu': talib.CDLMARUBOZU,
    'Mat Hold': talib.CDLMATHOLD,
    'Matching Low': talib.CDLMATCHINGLOW,
    'Modified Hikkake Pattern': talib.CDLHIKKAKEMOD,
    'Morning Doji Star': talib.CDLMORNINGDOJISTAR,
    'Morning Star': talib.CDLMORNINGSTAR,
    'On-Neck Pattern': talib.CDLONNECK,
    'Piercing Pattern': talib.CDLPIERCING,
    'Rickshaw Man': talib.CDLRICKSHAWMAN,
    'Rising/Falling Three Methods': talib.CDLRISEFALL3METHODS,
    'Separating Lines': talib.CDLSEPARATINGLINES,
    'Shooting Star': talib.CDLSHOOTINGSTAR,
    'Short Line Candle': talib.CDLSHORTLINE,
    'Spinning Top': talib.CDLSPINNINGTOP,
    'Stalled Pattern': talib.CDLSTALLEDPATTERN,
    'Stick Sandwich': talib.CDLSTICKSANDWICH,
    'Takuri (Dragonfly Doji with very long lower shadow)': talib.CDLTAKURI,
    'Tasuki Gap': talib.CDLTASUKIGAP,
    'Three Advancing White Soldiers': talib.CDL3WHITESOLDIERS,
    'Three Black Crows': talib.CDL3BLACKCROWS,
    'Three Inside Up/Down': talib.CDL3INSIDE,
    'Three Outside Up/Down': talib.CDL3OUTSIDE,
    'Three Stars In The South': talib.CDL3STARSINSOUTH,
    'Three-Line Strike': talib.CDL3LINESTRIKE,
    'Thrusting Pattern': talib.CDLTHRUSTING,
    'Tristar Pattern': talib.CDLTRISTAR,
    'Two Crows': talib.CDL2CROWS,
    'Unique 3 River': talib.CDLUNIQUE3RIVER,
    'Up/Down-gap side-by-side white lines': talib.CDLGAPSIDESIDEWHITE,
    'Upside Gap Two Crows': talib.CDLUPSIDEGAP2CROWS,
    'Upside/Downside Gap Three Methods': talib.CDLXSIDEGAP3METHODS
}
